# ==================================================================================================================== #
#                                                                                                                      #
#                      ████████   ███           █████          █████                 ████  ████                        #
#                      ███░░░░███ ░░░           ░░███          ░░███                 ░░███ ░░███                       #
#                     ░███   ░░░  ████           ░███   ██████  ░███ █████ █████ ████ ░███  ░███                       #
#                     ░█████████ ░░███           ░███  ███░░███ ░███░░███ ░░███ ░███  ░███  ░███                       #
#                     ░███░░░░███ ░███           ░███ ░███████  ░██████░   ░███ ░███  ░███  ░███                       #
#                     ░███   ░███ ░███     ███   ░███ ░███░░░   ░███░░███  ░███ ░███  ░███  ░███                       #
#                     ░░████████  █████   ░░████████  ░░██████  ████ █████ ░░███████  █████ █████                      #
#                     ░░░░░░░░  ░░░░░     ░░░░░░░░    ░░░░░░  ░░░░ ░░░░░   ░░░░░███ ░░░░░ ░░░░░                        #
#                                                                          ███ ░███                                    #
#                                                                          ░░██████                                    #
#                                                                                                                      #
#  6i Jekyll configuration - v1.0.0                                                                                    #
#                                                                                                                      #
#  More information :                                                                                                  #
#   - https://github.com/v20100v/6i-Jekyll#configuration                                                               #
#   - https://jekyllrb.com/docs/configuration/                                                                         #
#                                                                                                                      #
#  Don't forget to restart the server process, when you edit this file.                                                #
#                                                                                                                      #
# ==================================================================================================================== #


# ┌────────────────────┐ #
# │                    │ #
# │ Site configuration │ #
# │                    │ #
# └────────────────────┘ #

title: '6i Jekyll'            # Site's title, used as part of the tile tad in jekyll-seo-tag
encoding: utf-8               # Site's encoding
favicon: assets/favicon.ico   # Site's favicon
lang: en-US                   # Set the default site language
# url:                        # Base hostname for your site e.g. 'https://6i-jekyll.github.io'
# baseurl: ''                 # Subpath of your site, e.g. '/mySite/

# URL to a site-wide logo (e.g., /assets/your-company-logo.png) - If you would like the "publisher" property to be
# present, you must add this field to your site's configuration, during the validation of the structured data by Google
# Search Console - used in jekyll-seo-tag
logo: /assets/6i-Jekyll-banner_1500x500.jpg
# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome
# Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated
# to reviewing cat gifs that would be used when page.title is not defined - used in jekyll-seo-tag
tagline: 6i Jekyll theme for blog & IT projects portfolio
# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own
# description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: >-
  Ideas, imagine, impulse, innovate, implement & improve


# ┌─────────────────────┐ #
# │                     │ #
# │ Theme configuration │ #
# │                     │ #
# └─────────────────────┘ #

# theme: '6i-Jekyll' # Jekyll theme with gem-based method

# -------------
#  Custom text
# -------------
custom_text:
  footer: "Copyright &copy; <a href='https://github.com/v20100v/6i-Jekyll'>6i</a> - <span class='year'>2021</span>"

# --------------
#  Resume/CV
# --------------
# To write your resume (profil, experiences, degrees, publications...) fill the file '_data/resume.yml'
resume:
  enable: false

# --------------
#  Social items
# --------------
social:
  # "Social share" buttons in footer
  share_buttons:
    twitter: true
    linkedin: true
    facebook:
    email: true

  # "Follow me", "email" and "RSS" buttons in footer
  rss: true
  email_address: vb20100bv@gmail.com
  github: 'v20100v'
  twitter:
  facebook:
  linkedin: 'v20100v'

# ---------------
#  Web analytics
# ---------------
# Handle tracker web analytics (Google Tags, Google Universal Analtics or Matomo)
# Trackers is enable only in production environment, or if 'enable_in_dev' is true.
web_analytics:
  enable_in_dev: false
  google:
    gtag:
      tracking_id: UA-xxxxxxxxx1
      anonymize_ip: true
    universal:
      tracking_id: UA-xxxxxxxxx2
      anonymize_ip: true
#  matomo:
#    url: # your server Matomo URL
#    tracking_id: # the id site of the website you are tracking in Matomo


# ┌──────────────────────┐ #
# │                      │ #
# │ Jekyll configuration │ #
# │                      │ #
# └──────────────────────┘ #

# To set all available settings in Jekyll
# See https://jekyllrb.com/docs/configuration/options/

future: true                      # Publish posts or collection documents with a future date.
# show_drafts: true               # Process and render draft posts.
# unpublished: false              # Process and render posts that were marked as unpublished.
excerpt_separator: <!--more-->    # Default Marks end of excerpt in posts

# --------------------
#  Syntax highlighter
# --------------------
# In 6i, we disable Rouge syntax highlighter in order to replace it by another engine Prism.js
# Be aware if you used a Jekyll webiste hosted on Github Pages. In this case, we need
# some hack in configuration to disable Rouge, bu adding folowing lines.
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# ----------------
#  Jekyll plugins
# ----------------
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-include-cache

# -------------------------
#  Exclude from processing
# -------------------------
exclude:
  - './*.js'
  - '*.gemspec'
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - yarn.lock
  - doc/
  - test/

# --------------------------
#  Custom Jekyll collection
# --------------------------
collections:
  projects:
    output: true
    permalink: /:collection/:path

# -------------------------------------
#  Front matter defaults configuration
# -------------------------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# ---------------------------
#  Plugin jekyll-paginate-v2
# ---------------------------
# See https://github.com/sverrirs/jekyll-paginate-v2
pagination:
  enabled: true
  collection: 'posts'
  per_page: 2
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'

# --------------------------------
#  Plugin jekyll-feed (Atom feed)
# --------------------------------
# See https://github.com/jekyll/jekyll-feed
# To generate an Atom feed at /feed.xml, just add {% feed_meta %} into your head tag.
rss:
  path: feed.xml
feed:
  posts_limit: 20

# -------------------------------------------------------------
#  Plugin jekyll-sitemap (Generate sitemap for search engines)
# -------------------------------------------------------------
# See https://github.com/jekyll/jekyll-sitemap
# Sitemaps are an easy way to inform search engines about pages on their sites that are available for crawling.
# This plugin is used to silently generate a sitemaps.org compliant sitemap. If you would like to exclude specific
# pages/posts from the sitemap, just set the sitemap flag to false in the front matter for the page/post.

# ------------------------------------------------
#  Plugin jekyll-email-protect (Protection email)
# ------------------------------------------------
# See https://github.com/vwochnik/jekyll-email-protect
# Plugin to email protection liquid filter which can be used to obfuscate mailto: links to protect from spam bots.
# In your markup, simply use the encode_email liquid filter made available through this plugin
# <a href="mailto:{{ site.email | encode_email }}" title="Contact me">Contact me</a>

# -----------------------------------------------------------------------------------
#  Plugin jekyll-seo-tag (Add metadatas tags for search engines and social networks)
# -----------------------------------------------------------------------------------
# See https://github.com/jekyll/jekyll-seo-tag